### ISSUE TITLE
RestSimulationStreamSink.Create returns 

### ISSUE THREAD

**Issue by LimingRenPA** [MicrosoftDocs/mixed-reality#524]
I have the hololens 2 emulator installed on my WIndows machine. The emulator starts fine and I can access the device portal
![image](https://user-images.githubusercontent.com/74560586/154764097-70196da5-982a-44fd-9a87-71a925f79332.png)

I also installed the emular cert on my host machine.  But the below call fails. Need help to pass this error, thanks

                    sink = await RestSimulationStreamSink.Create(
                        // use the IP address for your device/emulator
                        new Uri(@"https://MY_EMULATOR_IP"),
                        ///new Uri(@"https://localhost"),
                        // no credentials are needed for the emulator
                        new System.Net.NetworkCredential("", ""),
                        // normal priorty
                        true,
                        // cancel token
                        token); ;

raised an exception:

Microsoft.PerceptionSimulation.PerceptionRequestException: HTTP request failed: CSRF Token Invalid
   at Microsoft.PerceptionSimulation.RestShared.ThrowExceptionForFailure(HttpResponseMessage msg)
   at Microsoft.PerceptionSimulation.RestSimulationStreamSink.Create(Uri uri, NetworkCredential credentials, Boolean normal, CancellationToken cancellationToken, StreamDataTypes streamDataTypes)
   at PerceptionSimulation.Program.<>c.<<Main>b__0_0>d.MoveNext() in D:\Tests\PerceptionSimulation\Program.cs:line 22

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aec8bc9f-8879-7158-99e8-5ae1eeacfd88
* Version Independent ID: aec8bc9f-8879-7158-99e8-5ae1eeacfd88
* Content: [Perception simulation - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/perception-simulation-overview)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/perception-simulation-overview.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/perception-simulation-overview.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @pbarnettms
* Microsoft Alias: **pbarnett**

**Comment by pbarnettms** [comment]
The emulator's Device Portal is configured for http by default, not https.  Please update the Uri in your code to use http://.   I was able to reproduce the token error when specifying https on the client with the server configured for http and confirmed that the connection was successful when I specified http.

**Comment by LimingRenPA** [comment]
Tried "http://my_Emulator_IP",  no port,  the below call raise a different exception:

                sink = await RestSimulationStreamSink.Create(
                    // use the IP address for your device/emulator
                    new Uri(@"https://MY_EMULATOR_IP"),
                    new System.Net.NetworkCredential("", ""),
                    true,
                    token); ;
Press any key to exit...
^ZSystem.Exception: WinHttpSendRequest: 12029
   at Microsoft.PerceptionSimulation.BinaryWebSocket.Connect(CancellationToken cancellationToken)
   at Microsoft.PerceptionSimulation.PerceptionSimulationRest.CreateControlStreamWebSocket(Uri uri, NetworkCredential credentials, String streamId, CancellationToken cancellationToken)
   at Microsoft.PerceptionSimulation.RestSimulationStreamSink.Create(Uri uri, NetworkCredential credentials, Boolean normal, CancellationToken cancellationToken, StreamDataTypes streamDataTypes)
   at Microsoft.PerceptionSimulation.RestSimulationStreamSink.Create(Uri uri, NetworkCredential credentials, Boolean normal, CancellationToken cancellationToken, StreamDataTypes streamDataTypes)
   at PerceptionSimulation.Program.<>c.<<Main>b__0_0>d.MoveNext() in D:\Tests\PerceptionSimulation\Program.cs:line 22

D:\Tests\PerceptionSimulation\bin\x64\Debug\net5.0\PerceptionSimulation.exe (process 22184) exited with code -1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.

**Comment by LimingRenPA** [comment]
Sorry,  I did not edit it correctly when trying to remove my ip address.
This is my code which gives 12029, it breaks in the exception block (12029)
![image](https://user-images.githubusercontent.com/74560586/154772482-87e23658-28b4-471e-ae83-6bf9eef5befc.png)

**Comment by pbarnettms** [comment]
From where are you getting the emulator's IP address?  Are you using the address from the Tools popup (click >> and go to 'Network') that's listed as "Emulator Adapter #1"?  This should be the same address that shows in your browser address bar when you launch Device Portal from the emulator (using the globe button).  Also, are you running your test code on the same PC as the emulator?  By default you cannot connect to the emulator from a separate PC but it can be configured allow that.

**Comment by LimingRenPA** [comment]
(1) Same PC, I am running the code from the host PC.
(2) The ip address is from the Device Portal 
![image](https://user-images.githubusercontent.com/74560586/154773530-e65407c3-75b9-4193-931e-59cbf70ef10a.png)

**Comment by pbarnettms** [comment]
The "SSL connection" showing as required is a UI bug in Device Portal.  SSL is not required in the emulator.  I am unable to reproduce your issue, even using the exact same build of the emulator.  I *can* reproduce the "CSRF token invalid" error if I specify https on the client when it shouldn't be, but the connection succeeds when using http.

 What operating system are you using on your desktop/host machine?  Is it possible that your IT department has policies in place restricting connections or that your machine is either behind on Windows Updates or is running preview updates?  (There have been a few changes in Windows networking that in theory could affect the scenario, particularly if your machine is far behind on updates.)

**Comment by LimingRenPA** [comment]
Thanks for your help. Did you use the same code RestSimulationStreamSink.Create?

My windows OS:
![image](https://user-images.githubusercontent.com/74560586/154777157-2357e52c-2b0e-44d1-900a-b93e5c74e327.png)
It has all the updates (not win 11):
![image](https://user-images.githubusercontent.com/74560586/154777241-454f3318-ca54-4b22-a56b-434eab9176a1.png)

**Comment by pbarnettms** [comment]
Yes, I used RestSimulationStreamSink.Create as written in the sample code in the documentation, using my emulator's IP address.  After it successfully connected I allow the sample code to run to completion, which included minimal interactions with the HoloLens, such as hiding and re-displaying the holographic Start menu.

Since it sounds like you toggled at least the SSL connection in Device Portal in the emulator, have you tried closing and restarting the emulator?  Note that upon restart it might be assigned a new IP address so you'll need to update your code, and any changes you made will be reverted to the default.

**Comment by LimingRenPA** [comment]
Yes, i did a few times:
(1)  restart &get the new ip address from click >> and go to 'Network') that's listed as "Emulator Adapter @1".
(2) change the ip address in the code.
the code still gives 12029.   
I am actually in Redmond, WA.  Is it possible I share my desktop with you sometime next week if I cannot figure out?

Have a great weekend

**Comment by pbarnettms** [comment]
I'm glad you were able to get it working on other machines.  If you want to get it working on the first machine I'd recommend focusing on the network settings and policies on that machine.  Does it have multiple adapters or special firewall configuration or software not present on the other machines, or a special proxy configuration, for example?
